# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:13
from __future__ import unicode_literals

import HIR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0002_auto_20160707_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=HIR.models.organization_directory_path),
        ),
    ]
