# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0003_auto_20160707_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='HIR.Residency'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='required',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='HIR.Residency'),
        ),
    ]
