# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0004_auto_20160712_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HIR.Organization'),
        ),
        migrations.AlterField(
            model_name='video',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='HIR.Organization'),
        ),
    ]
