# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0005_auto_20160712_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to='HIR.Organization'),
        ),
    ]
