# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0007_auto_20160714_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([]),
        ),
    ]
