# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIR', '0010_auto_20160714_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
